### PR TITLE
updated code for tanod-lupon backend

### PR DESCRIPTION
**Pull request by charlzzB**
hellloo ito nalang branch for checking tanod-lupon backend operations hehe

to check: 
- download the files and import the .json files to mongo db (I added a userData file for tanod and lupon acc)
- install npm init and npm i express express-handlebars body-parser mongoose then type index.js
- things that are still bugged : changing the pages in the dashbaord

### CODE REVIEW

**Comment by 1bellaa** [comment]
1. tanod
- hindi maayos yung columns
image

- when i choose to edit a tanod case... 
image

ang lumalabas ay resolved na siya kahit di pa naman napapalitan. can we fix this part?
image

- can we only have 10 records per page na ipapakita? para when there are more than 10 records, the user can just click on the arrow at the bottom 

- creating a new record: nawala ata yung icons?
image

- when creating a new record, hindi siya nag-rereflect sa database. pls double check po

2. lupon
- pls fix the columns
image

(same comments as tanod)

3. overall
- 'yung background for creating, deleting, editing cases: hindi naka-dark green 'yung background (@albarr15)

**Comment by charlzzB** [comment]
hii connected na ung tanod-lupon side to mongo atlas, please check the CRUD functionalities plus the searching of names ung the tanod and lupon dashboard

Things fixed:
- added the icons to the save changes and discard changes when creating a case for both tanod and lupon
- display  the respective status of the case when editing
- 10 records per page na pinapakita
- all cases created are stored in the db

Things to be fixed/do:
- frontend of the dashboard (ako na magaayos)
- merge with the recent admin side of the backend (mamaya na imerge pag oks na lahat) 

Notes: 
- for the dashboard if wala ung edit symbol meaning the case cant be edited anymore kasi resolved na siya bali magpapakita nalang siya if ongoing pa status ( will fix the css of that aswell hehe) 
- according to figma ung mga headers ng create and editing naka light green ung header at dark ung bg

**Comment by 1bellaa** [comment]
1. tanod
- yung arrow for entry # and date, hindi pa talaga gumagana for filtering noh?
image

- when i search tapos walang lalabas, pwede we make the highlighted part as "page 1" instead of "page 1 of 0"
image

2. lupon
- when i try to click the ongoing button on a record, hindi siya nagiging resolved
image

**Comment by charlzzB** [comment]
hi fixed all the bugs na about sa comment mo, bali css nalang kulang

**Comment by charlzzB** [comment]
hello I combined the tanod and lupon end to the ones in the main branch, paki check nalang hehe

**Comment by 1bellaa** [comment]
1. tanod
- can we align the entry # similar to how u did it sa date? 
image

- the button for filtering by date and entry # works naman, pero for example i tried to filter it by entry # tapos i click the arrow button sa baba, bumabalik s'ya sa default lineup. 
image

**Comment by 1bellaa** [comment]
- ask ko lang how the sorting works when creating a new record for both tanod and lupon. when i create another record for tanod, nalalagay sa pinakaunang row ng page 1 yung bago. on the other hand, nalalagay sa dulo when i create another record for lupon.
(lupon)
image

(tanod)
image

kasi for admin-lupon and admin-tanod, nalalagay yung mga bagong records sa dulo

**Comment by charlzzB** [comment]
Yung lupon di ko nilagyan ng sorting kasi wala naman arrows sa design kaya nalalagay sa dulo.  While sa lupon defualt sort niya  descending na entry number kaya pagka add ng record it gets sorted na pag bumabalik sa dashboard.

**Comment by 1bellaa** [comment]
for add accounts, can we have a top and bottom padding for the aesthetics lang lol para even yung space like with the left and right
image

**Comment by charlzzB** [comment]
Hii! Added the pages for the accounts view.

**Pull request merged**
