### PR TITLE
Add accounts pages

### PR DESCRIPTION
**Pull request by albarr15**
Implemented new buttons in Admin homepage and Accounts Database Pages
- Read, and Edit functions implemented for Accounts
- Added simple form validation when editing account details
- 
Notes:
- Image background is not same as Figma for now. I'll fix it in a diff. branch along with the other revisions
- Email and passwords are hardcoded (only visual, no db yet)

### CODE REVIEW

**Comment by 1bellaa** [comment]
- ganito ba talaga yung columns for the admin accounts? and idt may edit function for the accounts
image

- idt brgy. certificates button is clickable. hindi pa ba implemented ito?

**Comment by albarr15** [comment]
- Ganto dapat yung table for admin accounts: 
Screenshot 2024-07-11 at 9 37 47 PM 
for editing accounts naman pwede dapat siya by clicking View Account>Edit Data from accounts db view

- for Brgy. Certificates, not yet implementedd

**Comment by albarr15** [comment]
Ay btww, feel free to review and merge ung branch na 'to after Sprint 3 prio muna yung sa backendd, thank youuu

**Comment by 1bellaa** [comment]
- whenever we make changes to our account, i think dapat hindi nakalagay yung previous password natin. 
image

- pansin ko when i logged in sa kahit anong role, kahit @ lang ilagay ko sa email tapos 12345678 ang password, navavalidate niya. can we have a validation na regex para hindi basta-basta ma-aaccess 'yung webpage? 

- pls lmk if barangay certs is implemented na :>

**Pull request closed without merging**
