### PR TITLE
Combined backend branch

### PR DESCRIPTION
**Pull request by r4eiou**
Full implementation of the backend:
- Employee & Admin Operations
- Certificate Printing/Generation

Not yet implemented:
- Add account
- Certificate database

### CODE REVIEW

**Comment by 1bellaa** [comment]
1. employee page
- from search, bakit need pa i-hover para malaman na no results found? can we fix the UI for this pls :>
image

and di ba dapat merong "continue to..." eme? here's the figma version
image

- from search, bakit na-eedit 'to? hindi ba dapat fixed value 'to and hindi editable by the employee? (accessed this page by searching the name of juan and clicking on the name)
image

- for cert generation, 'yung mga dates, dapat yung huling day na ma-aaccess/mapipindot is the current date. pls edit this accordingly. may html attribute for this.
image

- for cert generation, 'yung placeholder for the date, can we make it DD/MM/YYYY para lang mas maganda tignan and change the color of the placeholder for dates similar to the other placeholder values
image

- for cert generation, hindi nag-rereflect yung uppercase letters from the form

ito 'yung input
image

ito yung kinalabasan
image

- for cert generation, hindi nag-reflect 'yung date of cert issuance (i think ito yung automated dapat na matik on the current day 'yung lalabas)
image

- for cert generation, good na meron pa rin nung validation thingy, but hindi ko ma-press yung close button? nawawala lang yung alert if i click outside the alert box, which is weird. can we make the close button work or remove it na lang if di na mapagana
image

2. admin page
- from admin lupon, bakit when i try to edit the details of a case, nawawala yung values na na-input na? hindi ba dapat may data na makikita
image

- from admin lupon, bakit lahat ng cases walang edit and mark as resolved button? lumalabas lang sila when i create a case record
image

- from admin tanod, bakit naging placeholder value yung dating data? dapat text value pa rin lalabas kasi what if may typo pala sa address? edi need pa nila i-type 'yung buong address instead of just typing a letter 
image

- from admin tanod and lupon, search function works. pero i wonder bakit clickable yung arrow eh isa lang naman 'yung result?
image

ito result when i click the arrow
image

- from accounts, dapat ba mawala rin yung email? oki lang if yung password mawawala when editing, pero for email i think oki lang if makita pa rin yung email na gamit nila
image

- from accounts, hindi clickable 'yung sidebar
image

3. login page
- for admin, nagbago 'yung button
image

4. overall
- hindi nag-rereflect sa mongodb when i edit, create, and delete a case

**Comment by r4eiou** [comment]
COMMENTS
**1. Employee Page**
- The search functionality is not yet complete. _[NOT YET DONE]_
- I have resolved all issues related to certificate generation, including setting the maximum date, fixing placeholders for the date, ensuring title case inputs reflect correctly, and fixing the date format issue in the certificate. I also removed the 'x' button, not sure why it stopped working.

image

- There is still one issue remaining with the CSS: the color of the input boxes, which I have yet to fix. (may inconsistency lang) _[NOT YET DONE]_

**2. Admin Page**
- If the case is already "resolved," buttons such as "mark as resolved" and "edit case" are hidden.
- When clicking the edit case button (ADMIN), the values remain but appear as placeholders. I have already fixed this for both Admin Tanod and Lupon.
- For both Admin Tanod and Lupon, the date issue (where the date disappears when the edit button is clicked) was a problem with the syntax. Some sample data had dates stored as mm/dd/yyyy instead of yyyy-mm-dd. I corrected this, and now it works fine. (you need to re-import tanod sample file)
- I'm still trying to figure out how to hide the second page in the search function.. _[NOT YET DONE]_
- For all accounts, the email value no longer disappears.
- Regarding the side buttons on the Accounts page, I haven't finished them yet because I am still waiting for the "Add Account Page." _[NOT YET DONE]_

**3. Admin Log In Page**
- Fixed the submit button.

**4. Overall**
-  Everything works well for me. Edits, creations, and deletions are reflected in MongoDB. You may just need to refresh it (mongodb).

**Comment by 1bellaa** [comment]
1. onClick page

noted! pero can we follow how it's done sa figma please :>
image
image

kasi parang naulit lang yung prompt
image

2. goods na 'yung iba. thank you for fixing these agad!! :>

**Comment by r4eiou** [comment]
1. fixed onClick page warning
2. done implementing search function in employee page (tho baka may bug)
3. added admin login warning

**Comment by 1bellaa** [comment]
1. Employee Pages

a. Check Clearance page
- Whenever I search for a name na "not found" and removed the name from the search bar (kunyare to search for another name), hindi nawawala yung option to go to certificate generation. Is it okay na we implement smth na when we remove a name sa search bar, mawawala yung option?
image

- when i search for a name that is found in the database (e.g., Anna), may lalabas na option. pero if i choose to remove the name from the search bar, hindi nawawala yung list of result. ^same request as abovementioned
image

- can we follow the interface from our Figma design? the one implemented rn has a space kasi
(figma)
image

(implemented)
image

2. Tanod Pages
- kindly align the columns pls :>
image

- can we also have 10 records per page lang din like sa admin-lupon, admin-tanod :>

- not reflecting changes sa mongodb when editing, deleting

- walang icons
image

- all of these not working
image

3. Lupon Pages

- same comments as ^tanod

4. Admin Pages

a. lupon pages
- i search for a name that is not found on the database. can we make this
image

page 1 lang sana ang nakalagay and not "page 1 of 0"?
image

b. tanod pages
- search not working

c. accounts
- sidebar not working pa rin?
image

- may bug ata
image

- clarify ko lang, when we edit the password, ano yung dapat ilalagay sa Password and Confirm Password field?
image

d. brgy certificates
- bump on this lang :>

5. Login Pages
- ask ko lang why we choose to implement the warning message differently for when there is no email/password inputted (former, wherein may pop up alert) vs when the user inputs the correct email pero wrong password (latter, nasa mismong page siya nalalagay)
 (former) 
image

 (latter)
image

**Comment by r4eiou** [comment]
**1. Employee Pages**
a. check clearance page
- The results disappear when there's no input na.
- fixed css: removed space and box-radius 
image

- On my end, if the individual has a case in both Tanod and Lupon, it displays properly. For example: 'Michael E. Jones.'
image

**2. - 3. Tanod & Lupon**
- For this, I think Ck already fixed it in the other pull request (the one for the Lupon and Tanod).

**4.  Admin Pages**
a. Instead of just "page 1", I did it like this na lang
image

b. Fixed Admin Tanod Search

c. Accounts
- Removed the sidebar (with permission from Clarissa). We decided to remove it because the purpose of the sidebar was to navigate to other role accounts. Initially, we thought there would only be one account per role. However, since it's possible to have multiple accounts per role (add account function- to be added), the sidebar is no longer necessary.
- works fine naman on my end.
image
- new password dapat iinput, para clear ginawa ko na lang na ganto yung label
image

d. still in progress sori 😭 

**5. Login Pages**
- I actually don't know, kasi nandun na yung nung na-receive ko yung files. But to make things uniform, let's use the latter option na lang. 
image
with this code, everything (mga warnings) displays na sa mismong page

NOTE:
- ginagawa ko pa yung  < forgot password? >

thank you so mu-

**Comment by 1bellaa** [comment]
1. employee page

a. check clearance
- may mga iba na hindi both lupon and tanod cases ang nakikita
image
image
image

2-3. gotchu tysm!!

4. admin

a. accounts
- oki i think good call na rin for removing the sidebar. if that's the case, can we remove the green part na lang din para yung white na lang yung kita and nakagitna
image

- idk whats up with mine but it's still like this when i try to edit lmfao
image

all slayed, thank u so mu-

**Comment by albarr15** [comment]
For #4:
- Removed the sidebar for individual account pages naa
image


- Forgot to update din pala pero I finished implementing yung regex for password and email validation na eto ung set rules for password:
1. minimum 8-characters length ("abcdefg" - 7 characters)
2. At least 1 letter
3. At least 1 digit
- Narevise ko na rin yung error message for this para mas descriptive:
image


tHANK YOUU GOODNIGHT 😭

**Comment by r4eiou** [comment]
**1. Employee Check Clearance**
Alliyah said na it's possible for an individual to have only one case (either Lupon or Tanod), and if that's the case daw, the column where they have no case will be hidden or removed. 

a. For "John **D.** Doe", sa Tanod lang siya may case. Si "John **A.** Doe yung meron sa both DB 
b. For "Anna E. Luna", sa Tanod lang din siya may case.
c. Same din kay "Mark Y. Young", sa Lupon lang siya may case.

**4. Admin: Accounts Page**
na-edit na ni Clarissa 🫡 

thank you so mu- 😆

**Pull request merged**
