### PR TITLE
added checkers when submitting tanod case

### PR DESCRIPTION
**Pull request by charlzzB**
Hello I added some code lang to prevent the same tanod case EntryNo from being repeated sa db when creating a case. For both tanod and admin side na meron.

### CODE REVIEW

**Comment by charlzzB** [comment]
hii added alert feature na sa tanod side only mej nahihirapan ako sa admin side hehe standby nalang for that.

**Comment by charlzzB** [comment]
hello added alert feature narin sa admin side. Bali what happens is that sa admin gumamit ng modal para ipakita yung mga errors or alerts while sa tanod side its just the normal alert.

**Comment by 1bellaa** [comment]
may napansin lang pala ako. whenever may isang field na kulang and i press "save changes," nawawala yung input sa lahat ng fields. oki lang ba if may validation din sa mga fields para hindi mawala yung na-input na 😭

**Comment by 1bellaa** [comment]
1. tanod & lupon
- i tried to edit a case tapos i left out one field na blank, clicked "save changes," pero na-save s'ya? oki lang ba if may validation din for this hehe
image

ito naman sa lupon and i removed info from two fields
image

**Comment by charlzzB** [comment]
helloo done adding validations when editing

**Comment by 1bellaa** [comment]
hi i think di nag-reflect yung changes sa admin-lupon and admin-tanod?

**Comment by charlzzB** [comment]
ayy sorry kala ko may validations narin un HAHAHA okok will edit din theree

**Comment by charlzzB** [comment]
helloo added narin dun sa admin side

**Comment by 1bellaa** [comment]
hi! admin-lupon case hindi nadedetect if may input or wala. nasasave s'ya kahit walang input
image

**Pull request merged**
