### PR TITLE
Generate certificate

### PR DESCRIPTION
**Pull request by r4eiou**
- fixed header
- fixed input bg color
-  fixed certificate layout and added underline

### CODE REVIEW

**Comment by 1bellaa** [comment]
- iirc when we presented nung sprint 3, may plans kayo to have the filename changed? tuloy pa rin ba ito?
image

- i think no need ng period here based doon sa template ng cert :>
image

- may additional space, can we remove it pls 
image
 
- im not sure i think we can omit the commas here since the date format is dd/mm/yyyy naman. pero pls confirm @AlliyahZulueta if need pa rin talaga ng comma
image

**Comment by r4eiou** [comment]
fixed na yung mga issues

note: dito ko na rin add yung certificate database (crud) - In progress

**Comment by 1bellaa** [comment]
- kapag hinabaan ko 'yung reason, nagcu-cut off s'ya sa cert
image
image

**Comment by r4eiou** [comment]
- hi fixed both reason and address, if nag-exceed, mag nenext line na
image

[hirap lang i-format 😭] 

di pa ayos: 
1. search bar cert db

**Pull request merged**
